gg.jte.development-mode=true
spring.application.name=MonsterAdoptionCenter

#Drop table if server is restarted
#This is a school project - There will be no important data loss
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#Allow larger files to be uploaded
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.tomcat.max-swallow-size=100MB
