gg.jte.development-mode=true
spring.application.name=MonsterAdoptionCenter

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB